
const species = [
    {
    id: 1,
    Nomecientifíco : "Caesalpinia echinata",
    Nomecomum: "Pau-Brasil",
    imagemcapa:'https://www.ibflorestas.org.br/wp-content/uploads/2010/07/pau-brasil-caesalpinia-echinata-225x300.jpg',
    imagemfruto:'https://1.bp.blogspot.com/-MXjjTnE2DUE/XWqWGP8xQzI/AAAAAAAA7mo/_8QBAIxdr2AU_u2AloD8nUWui03Kz9xNACLcBGAs/s1600/Pau_Brasil-Caesalpinia_%2Bechinata%2B%25283%2529.jpg',
    imagemarvore:'https://flora10.com.br/wp-content/uploads/2013/11/Pau-Brasil.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Dezembro a maio",
    Disperção: "Autocórica",
    Estado: "EN - em perigo"
},
{
    id: 2,
    Nomecientifíco : "Garcinia gardneriana",
    Nomecomum: "Bacupari",
    imagemcapa:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_gardneriana_Planch._%5E_Triana_Zappi_-_Flickr_-_Alex_Popovkin_Bahia_Brazil_9.jpg',
    imagemfruto:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_gardneriana_Planch._%5E_Triana_Zappi_-_Flickr_-_Alex_Popovkin_Bahia_Brazil_21.jpg',
    imagemarvore:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_macrophylla_1.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Novembro", 
    Floração: "Fevereiro",
    Disperção: "Zoocoria (por mamiferos) e Ictiocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 3,
    Nomecientifíco : "Posoqueria latifolia",
    Nomecomum: "Baga-de-Macaco",
    imagemcapa:'https://osa-arboretum.org/wp-content/uploads/2020/06/posoqueria_marco-768x1024.jpeg',
    imagemfruto:'https://www.colecionandofrutas.com.br/posoquerialatifolia_arquivos/image003.jpg',
    imagemarvore:'https://www.colecionandofrutas.com.br/posoquerialatifolia_arquivos/image002.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Janeiro a abril", 
    Floração: "Outubro a janeiro",
    Disperção: "Pequenos macacos e quatis",
    Estado: "LC - Categoria de ameaça: pouco preocupante"
},
{
    id: 4,
    Nomecientifíco : "Rapanea guianensis",
    Nomecomum: "Capororoca-do-Cerrado",
    imagemcapa:"https://fitoterapiabrasil.com.br/sites/default/files/styles/250home/public/img-148500.jpg?itok=O4_anGBK",
    imagemfruto:'https://www.frutosatrativosdocerrado.bio.br/images/especies/myrsine-guianensis.jpg',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a abril", 
    Floração: "Dezembro a janeiro",
    Disperção: "Zoocoria",
    Estado: "NE - Não ameaçada"
},
{
    id: 5,
    Nomecientifíco : "Inga edulis",
    Nomecomum: "Ingá-Cipó",
    imagemcapa:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image001.jpg',
    imagemfruto:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image003.jpg',
    imagemarvore:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image002.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Dezembro a março", 
    Floração: "Outubro a dezembro",
    Disperção: "Zoocoria e Hidrocoria",
    Estado: "-"
},
{
    id: 6,
    Nomecientifíco : "Licania tomentosa",
    Nomecomum: "Oiti-da-Praia",
    imagemcapa:'https://1.bp.blogspot.com/-GJGTg4zMNcU/XbO8y1YgzQI/AAAAAAAAJwY/udABNdCmCuYwHwAnzqOqXUvYc-g7Ms9HwCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas%2B12.jpg',
    imagemfruto:'https://1.bp.blogspot.com/-8aylHdmCf-M/XbO5qT2BGVI/AAAAAAAAJvs/NSoBcaDgnKUXeJGi6acRC5r97XrSwSmsQCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas%2B7.jpg',
    imagemarvore:'https://1.bp.blogspot.com/-wPFDNfsYuFE/XbO3654aJDI/AAAAAAAAJvI/EyNzUxX7KL0Mkro2pfF9YoodRAfjXFwfQCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a abril", 
    Floração: "Outubro",
    Disperção: "Autocórica e Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 7,
    Nomecientifíco : "Handroanthus serratifolius",
    Nomecomum: "Pau-d’Arco-Amarelo",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Handroanthus_serratifolius.jpg/280px-Handroanthus_serratifolius.jpg',
    imagemfruto:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Handroanthus_serratifolius_fruits.jpg/800px-Handroanthus_serratifolius_fruits.jpg',
    imagemarvore:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Flor_de_nuestra_tierra.JPG/220px-Flor_de_nuestra_tierra.JPG',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Setembro a outubro", 
    Floração: "Maio",
    Disperção: "Anemocórica",
    Estado: "NT - Quase ameaçada"
},
{
    id: 8,
    Nomecientifíco : "Piptadenia viridiflora",
    Nomecomum: "Surucucu",
    imagemcapa:'http://www.cnip.org.br/banco_img/Surucucu/piptadeniaviridiflorakunth5.jpg',
    imagemfruto:'http://www.remade.com.br/images/MadeirasExoticas/surucucu.png',
    imagemarvore:'http://www.cnip.org.br/banco_img/Surucucu/piptadeniaviridiflorakunth5.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Julho a outubro",
    Disperção: "Autocoria",
    Estado: "NE - Não ameaçada"
},
{
    id: 9,
    Nomecientifíco : "Vitex polygama",
    Nomecomum: "Tarumã-Açu",
    imagemcapa:'https://www.arvoresdobiomacerrado.com.br/site/wp-content/uploads/2017/07/1-36.jpg',
    imagemfruto:'https://www.colecionandofrutas.com.br/vitexpolygama_arquivos/image003.jpg',
    imagemarvore:'https://www.arvoresdobiomacerrado.com.br/site/wp-content/uploads/2017/07/3-35.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Janeiro a abril", 
    Floração: "Setembro",
    Disperção: "Zoocórica",
    Estado: "-"
},
{
    id: 10,
    Nomecientifíco : "Virola gardneri",
    Nomecomum: "Urucuba",
    imagemcapa:'https://biomaurbano.com.br/wp-content/uploads/2017/09/Urucuba-Virola-gardneri-A.DC_.-Warb.-3-681x1024.jpg',
    imagemfruto:'https://www.programaarboretum.eco.br/uploads/img/especies/152/especies_slide/610/thumb-800-450/1099d6b351a8b1a678aa89ac3cc2e1cc.jpg',
    imagemarvore:'https://www.programaarboretum.eco.br/uploads/img/especies/152/especies_slide/612/thumb-800-450/b345ae446446f13fcd708dab93294504.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Julho a outubro", 
    Floração: "Novembro a janeiro",
    Disperção: "Aves",
    Estado: "NE - Não ameaçada"
},
{
    id: 11,
    Nomecientifíco : "Luehea paniculata",
    Nomecomum: "Açoita-Cavalo",
    imagemcapa:'https://sobasombradasarvores.files.wordpress.com/2013/01/dsc05778.jpg?w=300',
    imagemfruto:'https://www.floresdocerrado.fot.br/outroslocais/foto2815a.jpg',
    imagemarvore:'http://www1.rc.unesp.br/igce/ceapla/atlasv3/flora/esp_flor_luehea2.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Durante todo ano", 
    Floração: "Durante todo ano",
    Disperção: "Anemocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 12,
    Nomecientifíco : "Andira fraxinifolia",
    Nomecomum: "Angelim-Doce",
    imagemcapa:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/maxfzepicrrxnwlvrde177pqpdazsc9wxktx58zkogivod08ru.jpg',
    imagemfruto:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/68gcwchvcc3jbvkut499t3sovghtbta3w7b4sfdxwd4vojy7si.jpg',
    imagemarvore:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/9e7ja4fegh8gfidatpca4ima87249symvwcfsm21je2vqf1v7t.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a março", 
    Floração: "Junho a agosto",
    Disperção: "Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 13,
    Nomecientifíco : "Cordia superba",
    Nomecomum: "Babosa-Branca",
    imagemcapa:'https://cdn.awsli.com.br/600x450/163/163535/produto/124320994/de012a2903e852d37a8e7915636c18ee-cygrc8ghqx.jpg',
    imagemfruto:'https://www.arvores.brasil.nom.br/new/babosabranca/cordia%20superba01.jpg',
    imagemarvore:'https://uenf.br/projetos/arvoresdauenf/files/2022/10/Babosa_branca.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Novembro a dezembro", 
    Floração: "Outubro a março",
    Disperção: "Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 14,
    Nomecientifíco : "Symphonia globulifera",
    Nomecomum: "Bulandi",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/d/df/Symphonia_globulifera_L._f.jpg',
    imagemfruto:'https://www.jardimcor.com/wp-content/uploads/2022/09/Symphonia_globulifera_L._f._-_Flickr_-_Alex_Popovkin_Bahia_Brazil_1.jpg',
    imagemarvore:'https://fm-digital-assets.fieldmuseum.org/1507/721/CLUS_symp_gl_per_15009.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Março a maio", 
    Floração: "Setembro a novembro",
    Disperção: "Autocórica e Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 15,
    Nomecientifíco : "Tabebuia aurea",
    Nomecomum: "Caraúba",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tabebuia_aurea_tree.jpg/280px-Tabebuia_aurea_tree.jpg',
    imagemfruto:'https://appverde.files.wordpress.com/2015/09/dsc07024.jpg?w=660',
    imagemarvore:'https://appverde.files.wordpress.com/2015/09/dsc01921.jpg?w=660',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a fevereiro", 
    Floração: "Setembro a novembro",
    Disperção: "Anemocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 16,
    Nomecientifíco : "Senna spectabilis var. excelsa",
    Nomecomum: "Cássia-do-Nordeste",
    imagemcapa:'https://imagemcampo.jbrj.gov.br/producao/imagens_de_campo/302922937.jpg',
    imagemfruto:'https://images.tcdn.com.br/img/img_prod/650041/sementes_de_cassia_do_nordeste_senna_spectabilis_mundo_das_sementes_201_6_20220221221458.jpg',
    imagemarvore:'https://imagemcampo.jbrj.gov.br/producao/imagens_de_campo/302922929.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Agosto a setembro", 
    Floração: "Novembro a abril",
    Disperção: "Autocórica e Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 17,
    Nomecientifíco : "Pityrocarpa moniliformis",
    Nomecomum: "Catanduva",
    imagemcapa:'https://4.bp.blogspot.com/-mBpXaojZogo/TzBBsKbt4gI/AAAAAAAAB-Q/-YriWU52TmQ/s400/IMG_1984.JPG',
    imagemfruto:'https://3.bp.blogspot.com/-lGaYzLk0k_Y/WMW50u4JhMI/AAAAAAAAlaE/ZbPaEH7X9Z8DdBi9YIv1lGZopGM_t4e2gCLcB/s320/Pityrocarpa%2Bmoniliformis%2B%25281%2529.jpg',
    imagemarvore:'https://4.bp.blogspot.com/-h1KIt5kFR34/Wqgi1NvTv4I/AAAAAAAA78c/JlpKpPE1l1weFds8RA6yjCPzGxG_bn2mQCLcBGAs/s320/DSCN5547.JPG',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Setembro", 
    Floração: "Março a junho",
    Disperção: "Autocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 18,
    Nomecientifíco : "Cedrela odorata",
    Nomecomum: "Cedro-Vermelho",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a junho", 
    Floração: "Dezembro a fevereiro",
    Disperção: "Anemocórica",
    Estado: "VU - Vulnerável"
},
{
    id: 19,
    Nomecientifíco : "Eschweilera ovata",
    Nomecomum: "Embiriba",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Dezembro a abril", 
    Floração: "Novembro a maio",
    Disperção: "Indefinida",
    Estado: "NE - Não ameaçada"
},
{
    id: 20,
    Nomecientifíco : "Alseis floribunda",
    Nomecomum: "Falsa-Pelada",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Julho a outubro", 
    Floração: "Julho a agosto",
    Disperção: "Autocórica e Zoocórica",
    Estado: "-"
},
{
    id: 21,
    Nomecientifíco : "Caesalpinia ferrea var. ferrea",
    Nomecomum: "Jucá",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Pequeno",
    Frutificação: "Agosto", 
    Floração: "Junho a setembro",
    Disperção: "Autocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 22,
    Nomecientifíco : "Mimosa tenuiflora",
    Nomecomum: "Jurema-Preta",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Pequeno",
    Frutificação: "Dezembro a março", 
    Floração: "Julho a fevereiro",
    Disperção: "Autocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 23,
    Nomecientifíco : "Protium heptaphyllum",
    Nomecomum: "Almecegueira ",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a Abril", 
    Floração: "Setembro a novembro ",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 24,
    Nomecientifíco : "Samanea tubulosa",
    Nomecomum: "Bordão-de-velho",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Após estação chuvosa", 
    Floração: "Dezembro a março",
    Disperção: "Autocórica e zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 25,
    Nomecientifíco : "Lithrea molleoides",
    Nomecomum: "Bugreiro",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Dezembro", 
    Floração: "Agosto a outubro",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 26,
    Nomecientifíco : "Cecropia pachystachya",
    Nomecomum: "Embaúba",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Maio a junho", 
    Floração: "Dezembro a fevereiro",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 27,
    Nomecientifíco : "Albizia polycephala",
    Nomecomum: "Farinha-seca",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Maio a junho", 
    Floração: "Outubro",
    Disperção: "Autocórica",
    Estado: "LC- Pouco preocupante"
},
{
    id: 28,
    Nomecientifíco : "Guazuma ulmifolia",
    Nomecomum: "Mutamba",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a novembro", 
    Floração: "Novembro a abril",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 29,
    Nomecientifíco : "Parkia pendula",
    Nomecomum: "Visgueiro",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Novembro a março", 
    Floração: "Julho a setembro",
    Disperção: "Autocórica/ Barocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 30,
    Nomecientifíco : "Sorocea bonplandii",
    Nomecomum: "Cincho",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Outubro a dezembro", 
    Floração: "Maio a agosto",
    Disperção: "Sabiás/Araçaris",
    Estado: "NE- Não ameaçada"
},
{
    id: 31,
    Nomecientifíco : "Simarouba amara",
    Nomecomum: "Marupá",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a março", 
    Floração: "Outubro a dezembro",
    Disperção: "Autocórica/Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 32,
    Nomecientifíco : "Byrsonima sericea",
    Nomecomum: "Murici",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Março a abril", 
    Floração: "Setembro a abril",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 33,
    Nomecientifíco : "Pterocarpus rohrii",
    Nomecomum: "Sangueiro",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Novembro", 
    Floração: "Dezembro a março",
    Disperção: "Anemocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 34,
    Nomecientifíco : "Plathymenia reticulata",
    Nomecomum: "Vinhático",
    imagemcapa:'',
    imagemfruto:'',
    imagemarvore:'',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Setembro a fevereiro",
    Disperção: "Anemocórica",
    Estado: "LC- Pouco preocupante"
}
]

export default species;