
const species = [
    {
    id: 1,
    Nomecientifíco : "Caesalpinia echinata",
    Nomecomum: "Pau-Brasil",
    imagemcapa:'https://www.ibflorestas.org.br/wp-content/uploads/2010/07/pau-brasil-caesalpinia-echinata-225x300.jpg',
    imagemfruto:'https://1.bp.blogspot.com/-MXjjTnE2DUE/XWqWGP8xQzI/AAAAAAAA7mo/_8QBAIxdr2AU_u2AloD8nUWui03Kz9xNACLcBGAs/s1600/Pau_Brasil-Caesalpinia_%2Bechinata%2B%25283%2529.jpg',
    imagemarvore:'https://flora10.com.br/wp-content/uploads/2013/11/Pau-Brasil.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Dezembro a maio",
    Disperção: "Autocórica",
    Estado: "EN - em perigo"
},
{
    id: 2,
    Nomecientifíco : "Garcinia gardneriana",
    Nomecomum: "Bacupari",
    imagemcapa:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_gardneriana_Planch._%5E_Triana_Zappi_-_Flickr_-_Alex_Popovkin_Bahia_Brazil_9.jpg',
    imagemfruto:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_gardneriana_Planch._%5E_Triana_Zappi_-_Flickr_-_Alex_Popovkin_Bahia_Brazil_21.jpg',
    imagemarvore:'http://www.jardimcor.com/wp-content/uploads/2022/10/Garcinia_macrophylla_1.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Novembro", 
    Floração: "Fevereiro",
    Disperção: "Zoocoria/Ictiocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 3,
    Nomecientifíco : "Posoqueria latifolia",
    Nomecomum: "Baga-de-Macaco",
    imagemcapa:'https://osa-arboretum.org/wp-content/uploads/2020/06/posoqueria_marco-768x1024.jpeg',
    imagemfruto:'https://www.colecionandofrutas.com.br/posoquerialatifolia_arquivos/image003.jpg',
    imagemarvore:'https://www.colecionandofrutas.com.br/posoquerialatifolia_arquivos/image002.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Janeiro a abril", 
    Floração: "Outubro a janeiro",
    Disperção: "Pequenos macacos e quatis",
    Estado: "LC - pouco preocupante"
},
{
    id: 4,
    Nomecientifíco : "Rapanea guianensis",
    Nomecomum: "Capororoca-do-Cerrado",
    imagemcapa:"https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS7XS2ZCNumg4ScVgaVN4dSFxwckr7SM8hXDVM7TUfg_ZKig3HO",
    imagemfruto:'https://www.arvores.brasil.nom.br/new/inga/inga01.jpg',
    imagemarvore:'https://www.arvores.brasil.nom.br/new/inga/inga04.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a abril", 
    Floração: "Dezembro a janeiro",
    Disperção: "Zoocoria",
    Estado: "NE - Não ameaçada"
},
{
    id: 5,
    Nomecientifíco : "Inga edulis",
    Nomecomum: "Ingá-Cipó",
    imagemcapa:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image001.jpg',
    imagemfruto:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image003.jpg',
    imagemarvore:'https://www.colecionandofrutas.com.br/ingaedulis_arquivos/image002.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Dezembro a março", 
    Floração: "Outubro a dezembro",
    Disperção: "Zoocoria/Hidrocoria",
    Estado: "-"
},
{
    id: 6,
    Nomecientifíco : "Licania tomentosa",
    Nomecomum: "Oiti-da-Praia",
    imagemcapa:'https://1.bp.blogspot.com/-GJGTg4zMNcU/XbO8y1YgzQI/AAAAAAAAJwY/udABNdCmCuYwHwAnzqOqXUvYc-g7Ms9HwCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas%2B12.jpg',
    imagemfruto:'https://1.bp.blogspot.com/-8aylHdmCf-M/XbO5qT2BGVI/AAAAAAAAJvs/NSoBcaDgnKUXeJGi6acRC5r97XrSwSmsQCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas%2B7.jpg',
    imagemarvore:'https://1.bp.blogspot.com/-wPFDNfsYuFE/XbO3654aJDI/AAAAAAAAJvI/EyNzUxX7KL0Mkro2pfF9YoodRAfjXFwfQCLcBGAsYHQ/s640/Oiti%2Blicania%2Btomentosa%2Bmudas.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a abril", 
    Floração: "Outubro",
    Disperção: "Autocórica/Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 7,
    Nomecientifíco : "Handroanthus serratifolius",
    Nomecomum: "Pau-d’Arco-Amarelo",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Handroanthus_serratifolius.jpg/280px-Handroanthus_serratifolius.jpg',
    imagemfruto:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Handroanthus_serratifolius_fruits.jpg/800px-Handroanthus_serratifolius_fruits.jpg',
    imagemarvore:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Flor_de_nuestra_tierra.JPG/220px-Flor_de_nuestra_tierra.JPG',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Setembro a outubro", 
    Floração: "Maio",
    Disperção: "Anemocórica",
    Estado: "NT - Quase ameaçada"
},
{
    id: 8,
    Nomecientifíco : "Piptadenia viridiflora",
    Nomecomum: "Surucucu",
    imagemcapa:'http://www.cnip.org.br/banco_img/Surucucu/piptadeniaviridiflorakunth3.jpg',
    imagemfruto:'http://www.remade.com.br/images/MadeirasExoticas/surucucu.png',
    imagemarvore:'http://www.cnip.org.br/banco_img/Surucucu/piptadeniaviridiflorakunth5.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Julho a outubro",
    Disperção: "Autocoria",
    Estado: "NE - Não ameaçada"
},
{
    id: 9,
    Nomecientifíco : "Vitex polygama",
    Nomecomum: "Tarumã-Açu",
    imagemcapa:'https://www.arvoresdobiomacerrado.com.br/site/wp-content/uploads/2017/07/1-36.jpg',
    imagemfruto:'https://www.colecionandofrutas.com.br/vitexpolygama_arquivos/image003.jpg',
    imagemarvore:'https://www.arvoresdobiomacerrado.com.br/site/wp-content/uploads/2017/07/3-35.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Janeiro a abril", 
    Floração: "Setembro",
    Disperção: "Zoocórica",
    Estado: "-"
},
{
    id: 10,
    Nomecientifíco : "Virola gardneri",
    Nomecomum: "Urucuba",
    imagemcapa:'https://biomaurbano.com.br/wp-content/uploads/2017/09/Urucuba-Virola-gardneri-A.DC_.-Warb.-3-681x1024.jpg',
    imagemfruto:'https://www.programaarboretum.eco.br/uploads/img/especies/152/especies_slide/610/thumb-800-450/1099d6b351a8b1a678aa89ac3cc2e1cc.jpg',
    imagemarvore:'https://www.programaarboretum.eco.br/uploads/img/especies/152/especies_slide/612/thumb-800-450/b345ae446446f13fcd708dab93294504.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Julho a outubro", 
    Floração: "Novembro a janeiro",
    Disperção: "Aves",
    Estado: "NE - Não ameaçada"
},
{
    id: 11,
    Nomecientifíco : "Luehea paniculata",
    Nomecomum: "Açoita-Cavalo",
    imagemcapa:'https://sobasombradasarvores.files.wordpress.com/2013/01/dsc05778.jpg?w=300',
    imagemfruto:'https://www.floresdocerrado.fot.br/outroslocais/foto2815a.jpg',
    imagemarvore:'http://www1.rc.unesp.br/igce/ceapla/atlasv3/flora/esp_flor_luehea2.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Durante todo ano", 
    Floração: "Durante todo ano",
    Disperção: "Anemocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 12,
    Nomecientifíco : "Andira fraxinifolia",
    Nomecomum: "Angelim-Doce",
    imagemcapa:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/maxfzepicrrxnwlvrde177pqpdazsc9wxktx58zkogivod08ru.jpg',
    imagemfruto:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/68gcwchvcc3jbvkut499t3sovghtbta3w7b4sfdxwd4vojy7si.jpg',
    imagemarvore:'https://dwd92kep8i36h.cloudfront.net/sid/trees/87/9e7ja4fegh8gfidatpca4ima87249symvwcfsm21je2vqf1v7t.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a março", 
    Floração: "Junho a agosto",
    Disperção: "Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 13,
    Nomecientifíco : "Cordia superba",
    Nomecomum: "Babosa-Branca",
    imagemcapa:'https://cdn.awsli.com.br/600x450/163/163535/produto/124320994/de012a2903e852d37a8e7915636c18ee-cygrc8ghqx.jpg',
    imagemfruto:'https://www.arvores.brasil.nom.br/new/babosabranca/cordia%20superba01.jpg',
    imagemarvore:'https://uenf.br/projetos/arvoresdauenf/files/2022/10/Babosa_branca.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Novembro a dezembro", 
    Floração: "Outubro a março",
    Disperção: "Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 14,
    Nomecientifíco : "Symphonia globulifera",
    Nomecomum: "Bulandi",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/d/df/Symphonia_globulifera_L._f.jpg',
    imagemfruto:'https://www.jardimcor.com/wp-content/uploads/2022/09/Symphonia_globulifera_L._f._-_Flickr_-_Alex_Popovkin_Bahia_Brazil_1.jpg',
    imagemarvore:'https://fm-digital-assets.fieldmuseum.org/1507/721/CLUS_symp_gl_per_15009.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Março a maio", 
    Floração: "Setembro a novembro",
    Disperção: "Autocórica/Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 15,
    Nomecientifíco : "Tabebuia aurea",
    Nomecomum: "Caraúba",
    imagemcapa:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tabebuia_aurea_tree.jpg/280px-Tabebuia_aurea_tree.jpg',
    imagemfruto:'https://appverde.files.wordpress.com/2015/09/dsc07024.jpg?w=660',
    imagemarvore:'https://appverde.files.wordpress.com/2015/09/dsc01921.jpg?w=660',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Janeiro a fevereiro", 
    Floração: "Setembro a novembro",
    Disperção: "Anemocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 16,
    Nomecientifíco : "Senna spectabilis var. excelsa",
    Nomecomum: "Cássia-do-Nordeste",
    imagemcapa:'https://imagemcampo.jbrj.gov.br/producao/imagens_de_campo/302922937.jpg',
    imagemfruto:'https://images.tcdn.com.br/img/img_prod/650041/sementes_de_cassia_do_nordeste_senna_spectabilis_mundo_das_sementes_201_6_20220221221458.jpg',
    imagemarvore:'https://imagemcampo.jbrj.gov.br/producao/imagens_de_campo/302922929.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Agosto a setembro", 
    Floração: "Novembro a abril",
    Disperção: "Autocórica/Zoocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 17,
    Nomecientifíco : "Pityrocarpa moniliformis",
    Nomecomum: "Catanduva",
    imagemcapa:'https://4.bp.blogspot.com/-mBpXaojZogo/TzBBsKbt4gI/AAAAAAAAB-Q/-YriWU52TmQ/s400/IMG_1984.JPG',
    imagemfruto:'https://3.bp.blogspot.com/-lGaYzLk0k_Y/WMW50u4JhMI/AAAAAAAAlaE/ZbPaEH7X9Z8DdBi9YIv1lGZopGM_t4e2gCLcB/s320/Pityrocarpa%2Bmoniliformis%2B%25281%2529.jpg',
    imagemarvore:'https://4.bp.blogspot.com/-h1KIt5kFR34/Wqgi1NvTv4I/AAAAAAAA78c/JlpKpPE1l1weFds8RA6yjCPzGxG_bn2mQCLcBGAs/s320/DSCN5547.JPG',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Setembro", 
    Floração: "Março a junho",
    Disperção: "Autocórica",
    Estado: "DD - Deficiência de dados"
},
{
    id: 18,
    Nomecientifíco : "Cedrela odorata",
    Nomecomum: "Cedro-Vermelho",
    imagemcapa:'https://fm-digital-assets.fieldmuseum.org/1510/985/MELI_cedr_odor_fre_rf21.jpg',
    imagemfruto:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-UVCerQLmnRDVNJMGVwGhQSQJHGEJMQqfMpfas7B0ultiq7sPbODf5BarEEIIwYwKEjI&usqp=CAU',
    imagemarvore:'https://www.programaarboretum.eco.br/uploads/img/especies/63/especies_slide/209/thumb-800-450/cfde5e56f600b79f7ca9a01b8e118a23.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a junho", 
    Floração: "Dezembro a fevereiro",
    Disperção: "Anemocórica",
    Estado: "VU - Vulnerável"
},
{
    id: 19,
    Nomecientifíco : "Eschweilera ovata",
    Nomecomum: "Embiriba",
    imagemcapa:'https://www.funbio.org.br/wp-content/uploads/2020/05/10-Hinha%C3%ADba-Eschweilera-ovata.jpeg',
    imagemfruto:'https://www.programaarboretum.eco.br/uploads/img/especies/123/especies_slide/376/thumb-800-450/dc89e799ff7bdc314a1dc6bde8c26154.jpg',
    imagemarvore:'https://www.programaarboretum.eco.br/uploads/img/especies/123/especies_slide/379/thumb-800-450/12de19ff343b720af32aa346a6187dbb.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Dezembro a abril", 
    Floração: "Novembro a maio",
    Disperção: "Indefinida",
    Estado: "NE - Não ameaçada"
},
{
    id: 20,
    Nomecientifíco : "Alseis floribunda",
    Nomecomum: "Falsa-Pelada",
    imagemcapa:'https://www.arvores.brasil.nom.br/new/quinasaopaulo/quinasp01.jpg',
    imagemfruto:'https://www.arvores.brasil.nom.br/new/quinasaopaulo/quinasp03.jpg',
    imagemarvore:'https://www.arvores.brasil.nom.br/new/quinasaopaulo/quinasp02.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Julho a outubro", 
    Floração: "Julho a agosto",
    Disperção: "Autocórica/Zoocórica",
    Estado: "-"
},
{
    id: 21,
    Nomecientifíco : "Caesalpinia ferrea var. ferrea",
    Nomecomum: "Jucá",
    imagemcapa:'https://greensaopaulo.com.br/wp-content/uploads/2022/06/Pau-ferro-600x600.jpg',
    imagemfruto:'https://www.picturethisai.com/image-handle/website_cmsname/image/1080/365302799785394176.jpeg?x-oss-process=image/format,webp/resize,s_422&v=1.2',
    imagemarvore:'https://www.picturethisai.com/image-handle/website_cmsname/image/1080/157248721367597063.jpeg?x-oss-process=image/format,webp/resize,s_422&v=1.2',
    Ocorrência: "PE",
    Porte: "Pequeno",
    Frutificação: "Agosto", 
    Floração: "Junho a setembro",
    Disperção: "Autocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 22,
    Nomecientifíco : "Mimosa tenuiflora",
    Nomecomum: "Jurema-Preta",
    imagemcapa:'http://www.cnip.org.br/banco_img/Jurema%20Preta/mimosatenuiflorawilldpoir8.jpg',
    imagemfruto:'http://www.cnip.org.br/banco_img/Jurema%20Preta/mimosatenuiflorawilldpoir.jpg',
    imagemarvore:'http://www.cnip.org.br/banco_img/Jurema%20Preta/mimosatenuiflorawilldpoir4.jpg',
    Ocorrência: "PE",
    Porte: "Pequeno",
    Frutificação: "Dezembro a março", 
    Floração: "Julho a fevereiro",
    Disperção: "Autocórica",
    Estado: "NE - Não ameaçada"
},
{
    id: 23,
    Nomecientifíco : "Protium heptaphyllum",
    Nomecomum: "Almecegueira ",
    imagemcapa:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQr1MYpC-Gfe-jSi7zOX1mSrR7kYdpgzLprdSEpfdoYci4fNPn9',
    imagemfruto:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpdanTbLfjjukahbUWxmq_kK02b-e6q9hP3nA76_402_Ya81gA',
    imagemarvore:'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ1NNpL28fgpuWMiN7yJqhmRNHUicE9b-6Hm7kKolN4hMZwaExz',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a Abril", 
    Floração: "Setembro a novembro ",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 24,
    Nomecientifíco : "Samanea tubulosa",
    Nomecomum: "Bordão-de-velho",
    imagemcapa:'https://www.arvores.brasil.nom.br/new/setecascas/samanea%20tubulosa01.jpg',
    imagemfruto:'https://www.sementesarbocenter.com.br/upload/produto/imagem/b_sementes-de-abobreira-5.jpg?v=1',
    imagemarvore:'https://www.sementesarbocenter.com.br/upload/produto/imagem/b_sementes-de-abobreira-3.jpg?v=1',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Após estação chuvosa", 
    Floração: "Dezembro a março",
    Disperção: "Autocórica/Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 25,
    Nomecientifíco : "Lithrea molleoides",
    Nomecomum: "Bugreiro",
    imagemcapa:'https://imagemcampo.jbrj.gov.br/producao/imagens_de_campo/301000440.jpg',
    imagemfruto:'https://www.floralondrina.com.br/img/products/muda-de-bugreiro-lithraea-molleoides_1_1200.jpg',
    imagemarvore:'https://www.floralondrina.com.br/img/products/muda-de-bugreiro-lithraea-molleoides_2_1200.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Dezembro", 
    Floração: "Agosto a outubro",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 26,
    Nomecientifíco : "Cecropia pachystachya",
    Nomecomum: "Embaúba",
    imagemcapa:'https://www.arvores.brasil.nom.br/new/embauba/cecropia%20pachystachya01.jpg',
    imagemfruto:'http://www.frutosatrativosdocerrado.bio.br/images/especies/1-cecropia-pachystachya.jpg',
    imagemarvore:'https://florestaombrofilamista.com.br/sidol/photos/370/folha.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Maio a junho", 
    Floração: "Dezembro a fevereiro",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 27,
    Nomecientifíco : "Albizia polycephala",
    Nomecomum: "Farinha-seca",
    imagemcapa:'https://meioambiente.culturamix.com/blog/wp-content/uploads/2018/01/Angico-branco-Albizia-polycephala-500x333.jpg',
    imagemfruto:'https://www.programaarboretum.eco.br/uploads/img/especies/96/especies_slide/352/thumb-800-450/c9976d05e3c6e34b107b243b443c6032.jpg',
    imagemarvore:'https://2.bp.blogspot.com/-rj0lBsDURjs/WmcX9zISAgI/AAAAAAAA44I/hXKwBP1yy0YZyceGk6r1P4mqTZCM10zQACLcBGAs/s1600/Albizia%2Bpolycephala%2B%252825%2529.JPG',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Maio a junho", 
    Floração: "Outubro",
    Disperção: "Autocórica",
    Estado: "LC- Pouco preocupante"
},
{
    id: 28,
    Nomecientifíco : "Guazuma ulmifolia",
    Nomecomum: "Mutamba",
    imagemcapa:'https://cdn.pixabay.com/photo/2020/08/22/20/36/which-5509380_1280.jpg',
    imagemfruto:'https://cdn.awsli.com.br/2500x2500/998/998380/produto/37544668/2182390bf5.jpg',
    imagemarvore:'https://dw0jruhdg6fis.cloudfront.net/producao/31584919/G/whatsapp_image_2022_05_12_at_16.04.03_1.jpeg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a novembro", 
    Floração: "Novembro a abril",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 29,
    Nomecientifíco : "Parkia pendula",
    Nomecomum: "Visgueiro",
    imagemcapa:'https://media-cdn.tripadvisor.com/media/photo-s/1b/bf/5e/f0/icmbio.jpg',
    imagemfruto:'https://fm-digital-assets.fieldmuseum.org/2173/291/LA01038_08APR2020.jpg',
    imagemarvore:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5V6ONju6yOmJVRedDU0XS2zdnrLRbj0o-V4KbuvKgVCTo57avKvFfQ7wQFlCS_eKkXbQ&usqp=CAU',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Novembro a março", 
    Floração: "Julho a setembro",
    Disperção: "Autocórica/ Barocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 30,
    Nomecientifíco : "Sorocea bonplandii",
    Nomecomum: "Cincho",
    imagemcapa:'https://www.colecionandofrutas.com.br/soroceabomplandii_arquivos/image001.jpg',
    imagemfruto:'https://www.colecionandofrutas.com.br/soroceabomplandii_arquivos/image004.jpg',
    imagemarvore:'https://www.colecionandofrutas.com.br/soroceabomplandii_arquivos/image003.jpg',
    Ocorrência: "PE",
    Porte: "Médio",
    Frutificação: "Outubro a dezembro", 
    Floração: "Maio a agosto",
    Disperção: "Sabiás/Araçaris",
    Estado: "NE- Não ameaçada"
},
{
    id: 31,
    Nomecientifíco : "Simarouba amara",
    Nomecomum: "Marupá",
    imagemcapa:'https://lpf.florestal.gov.br/images/madeirasbrasileiras/Marupa1.jpg',
    imagemfruto:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTT0psg5wAwonGeNxmMCv5-vk_pBUinsrWZ1Q5D-GSsXJvm1oht',
    imagemarvore:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT5389Mv0twti6PkYLUzgpldunhyzzZZPego-f5LgPFfnLhVWss',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Fevereiro a março", 
    Floração: "Outubro a dezembro",
    Disperção: "Autocórica/Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 32,
    Nomecientifíco : "Byrsonima sericea",
    Nomecomum: "Murici",
    imagemcapa:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRNCpF9oA5qzQPh0QvtNzLrEbX38SCpBKKeiI-uCNwlu4enAG0_',
    imagemfruto:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS4hRJcVnm2P-xMWsm96eTAMQmL0ozkc1lY7g8dFt0IaWSED9eh',
    imagemarvore:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRt4lc0eeq_jXjkQte4PysSfL8dNxg5wDE2Ozcgwohmyhvbn7Vg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Março a abril", 
    Floração: "Setembro a abril",
    Disperção: "Zoocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 33,
    Nomecientifíco : "Pterocarpus rohrii",
    Nomecomum: "Sangueiro",
    imagemcapa:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRTiHQk_w4sTrOq5E9YSnwBKCxRlSoiD7WVTFZTRvs5VduwyD7z',
    imagemfruto:'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSCLeDcWCFq4CPoQN0QX8htMIExCFOC3DdTBRf86gGUEKG0An5t',
    imagemarvore:'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTCMdYQ-QAytTiA5f4iEJYiG19ZBxGkr54kxTMyVLqwV6Oc6-4d',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Novembro", 
    Floração: "Dezembro a março",
    Disperção: "Anemocórica",
    Estado: "NE- Não ameaçada"
},
{
    id: 34,
    Nomecientifíco : "Plathymenia reticulata",
    Nomecomum: "Vinhático",
    imagemcapa:'https://i0.wp.com/novamata.org/wp-content/uploads/2020/09/450px-Plathymenia_reticulata_amarelo_-_Flickr_-_Tarciso_Leao_2.jpg?w=450&ssl=1',
    imagemfruto:'https://content.eol.org/data/media/d5/e9/da/542.1ecd906cdd153ccf573646e7e931c486.260x190.jpg',
    imagemarvore:'https://content.eol.org/data/media/d6/4b/de/542.371289e636acba0847c6aba25f7871fc.260x190.jpg',
    Ocorrência: "PE",
    Porte: "Grande",
    Frutificação: "Outubro a janeiro", 
    Floração: "Setembro a fevereiro",
    Disperção: "Anemocórica",
    Estado: "LC- Pouco preocupante"
}
]

export default species;